# Step 1: Build the Go binary using the standard library profile
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Step 2: Create a minimal, lightweight container for execution
FROM alpine:latest  
WORKDIR /root/
COPY --from=builder /app/main .
COPY openapi.yaml . 
EXPOSE 8080
CMD ["./main"]
